// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwrzrgojacgtavuckcuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cnpyZ29qYWNndGF2dWNrY3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDMyMTUsImV4cCI6MjA3MDUxOTIxNX0.ctbdnNEXHNXSGCFdZwClV-Ey9kAldumXsQQ3AB0EVk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});